### PR TITLE
Update defconfig AF_XDP

### PR DESCRIPTION
**Pull request by psakhis**
Prepare kernel to work with AF_XDP sockets and BPF (CONFIG_XDP_SOCKETS=y)
Some xdp related patches on stmicro driver are needed to fix some stability issues. These patches are in current Linux kernel so i only applied them into actual 5.15 version.

https://github.com/torvalds/linux/commit/7f9b8fe5445cc3644a42c085421b3f123d78cf6e
https://github.com/torvalds/linux/commit/36371876e000012ae4440fcf3097c2f0ed0f83e7
https://github.com/torvalds/linux/commit/ac746c8520d9d056b6963ecca8ff1da9929d02f1
https://github.com/torvalds/linux/commit/fa02de9e75889915b554eda1964a631fd019973b
https://github.com/torvalds/linux/commit/884d2b845477cd0a18302444dc20fe2d9a01743e
https://github.com/torvalds/linux/commit/77711683a50477de39757d67ab1a3638220d6860
https://github.com/torvalds/linux/commit/087a7b944c5db409f7c1a68bf4896c56ba54eaff
https://github.com/torvalds/linux/commit/b270bfe697367776eca2e6759a71d700fb8d82a2
https://github.com/torvalds/linux/commit/61da6ac715700bcfeef50d187e15c6cc7c9d079b
https://github.com/torvalds/linux/commit/2d1a42cf7f77cda54dbbee18d00b1200e7bc22aa
https://github.com/torvalds/linux/commit/24e3fce00c0b557491ff596c0682a29dee6fe848

Tested with GroovyMiSTer core.

### CODE REVIEW

**Comment by psakhis** [comment]
I need to check if there are something wrong with my builded kernel. Seems SAMBA isn't working

cat: /lib/modules/5.15.1/modules.builtin: No such file or directory
The current Kernel doesn't
support CIFS (SAMBA).

**Comment by psakhis** [comment]
Nothing, just i builded with (-EXTRAVERSION) /lib/modules/5.15.1-MiSTer/

**Comment by sorgelig** [comment]
Why MiSTer needs it?

**Comment by psakhis** [comment]
AF_XDP can increase performance for networking vs traditional sockets.

GroovyMiSTer core uses Linux as udp server for receive packets and share data to fpga with ddr. Using AF_XDP performance increases about 30%.

**Comment by psakhis** [comment]
If kernel update is planned in the future maybe this PR isn't needed at all, just adding flags to support XDP will be enough.
EDIT:
CONFIG_XDP_SOCKETS=y
CONFIG_BPF_SYSCALL=y

**Comment by psakhis** [comment]
I close PR. I think kernel 5.15 isn't mature yet.

Testing ZEROCOPY mode fails.

**Pull request closed without merging**
