### PR TITLE
Add NFS4 to MiSTer_defconfig as discussed in #38

### PR DESCRIPTION
**Pull request by ojaksch**
see above

### CODE REVIEW

**Comment by sorgelig** [comment]
i've thought that discussion revealed that most V4 features aren't applicable nor good for MiSTer

**Comment by ojaksch** [comment]
No, not NFS4 per se, there (maybe) are the one or the other options that _could_ have a negative impact. In the discussion and in the PR we've left out these "maybes".
Personally I'm running my own NFS4 MiSTer Kernel for ~2 years w/o any issue.

**Comment by sorgelig** [comment]
ok

**Comment by ojaksch** [comment]
No hurry. While we're waiting for your NFS4 aware Kernel, I'll still patch and publish (if necessary) my own one at the forum ...

**Comment by sorgelig** [comment]
here is test release: 
https://github.com/MiSTer-devel/Main_MiSTer/issues/769#issuecomment-1520157907

**Pull request merged**
