### PR TITLE
Add support for TP-Link UB500 Adapter

### PR DESCRIPTION
**Pull request by birdybro**
https://www.spinics.net/lists/linux-bluetooth/msg94476.html

This should resolve this problem --> https://misterfpga.org/viewtopic.php?p=56469#p56469

I don't have a way to compile the linux kernel completely and I don't have that adapter, so I am unable to test it myself.

### CODE REVIEW

**Comment by birdybro** [comment]
Alternatively:

https://github.com/MiSTer-devel/Linux-Kernel_MiSTer/compare/MiSTer-v5.15...birdybro:bump-btusb-dev-5.15.4

Would this be more effective or preferable in your opinion?

**Comment by sorgelig** [comment]
Bumping version isn't a good solution for 1 line. It will require to check and test all tweaks.

**Comment by birdybro** [comment]
Thanks! I'll leave that branch up for reference in case users need it (maybe their adapter is in the list and I can check) later.

**Comment by christ776** [comment]
thanks for adding support for this Bluetooth dongle. I was the one who wrote about it on the forum. Please correct if I'm wrong, does this merge mean that whenever the next Linux update is being released, it should have this compiled into the kernel? thanks!

**Comment by sorgelig** [comment]
right

**Pull request merged**
