### PR TITLE
Update rtl drivers from upstream

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
[RTL-MiSTer-patch-11042023.zip](https://github.com/MiSTer-devel/Linux-Kernel_MiSTer/files/10946806/RTL-MiSTer-patch-11042023.zip)
Patch compiled for Current mister images

**Comment by ghost** [comment]
@sorgelig do the honors Please :)

**Comment by sorgelig** [comment]
Last time i've merged your changes and then had to spend time to make them able to be compiled as a modules.
Please make sure your changes will allow to be compiled by standard kernel compilation way. Make sure includes are correct.

**Comment by sorgelig** [comment]
i've pushed my fixes. So please take a look and make sure it's fixed in new versions. Make sure make && make modules are finished without errors/warnings.

**Comment by ghost** [comment]
@sorgelig  weird.
 i am always building those modules before  pr with 
 make ARCH=arm mrproper && make ARCH=arm MiSTer_defconfig && make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- EXTRAVERSION=-MiSTer modules -j5
the zip package with binary modules attached was  created that way.

**Comment by sorgelig** [comment]
This time it compiled without errors. Thanks!

**Comment by ghost** [comment]
next time, when i break something, please ping me, do not waste your time to fix my mistakes.
:)

**Pull request merged**
